### ISSUE TITLE
Error when executing readme code

### ISSUE THREAD

**Issue by pajachiet** [HDI-Project/SDV#82] opened 2019-02-01 10:27 UTC
* SDV version: https://github.com/pajachiet/SDV/blob/test-project/tests/sdv/test_readme.py
* Python version: 3.6.5
* Operating System: macOS Mojave 10.14

### Description

When trying to execute the readme code, I get the following error

### What I Did

Running this code, copied from the readme
https://github.com/pajachiet/SDV/blob/test-project/tests/sdv/test_readme.py

` python tests/sdv/test_readme.py`

I get the following error

```
Traceback (most recent call last):
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3414, in _ensure_valid_index
    value = Series(value)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/series.py", line 264, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1481, in __init__
    block = make_block(block, placement=slice(0, len(axis)), ndim=1)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 3095, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 2631, in __init__
    placement=placement)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 87, in __init__
    '{mgr}'.format(val=len(self.values), mgr=len(self.mgr_locs)))
ValueError: Wrong number of items passed 1, placement implies 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/sdv/test_readme.py", line 13, in <module>
    test_readme_code()
  File "tests/sdv/test_readme.py", line 6, in test_readme_code
    data_vault.fit()
  File "…/SDV/sdv/sdv.py", line 43, in fit
    self.dn.transform_data()
  File "…/SDV/sdv/data_navigator.py", line 131, in transform_data
    transformer_list=transformers, missing=missing)
  File "…/SDV/venv/lib/python3.6/site-packages/rdt/hyper_transformer.py", line 110, in fit_transform
    table, table_meta, transformer_dict, transformer_list, missing)
  File "…/SDV/venv/lib/python3.6/site-packages/rdt/hyper_transformer.py", line 175, in fit_transform_table
    new_col = t.fit_transform(col.to_frame(), field, missing)
  File "…/SDV/venv/lib/python3.6/site-packages/rdt/transformers/NumberTransformer.py", line 42, in fit_transform
    out[self.col_name] = col
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3360, in __setitem__
    self._set_item(key, value)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3434, in _set_item
    self._ensure_valid_index(value)
  File "…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3416, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
```

**Comment by ManuelAlvarezC** [comment] 2019-02-01 12:34
Thanks for reporting this issue @pajachiet.

I have been able to reproduce this issue locally using your fork, and it seems like  this is an issue caused by `RDT` rather than `SDV`. It also seems that is already solved and will be included in the next release to PyPI.

That being told, if you want to run the examples from the README, I can propose you the following solutions:

- Try it with the PyPI version
- Use the latest development version of RDT.
- Use pandas==0.2.0

**Comment by pajachiet** [comment] 2019-02-01 13:19
Thanks a lot for this quick answer ! Using development version of RDT works

` pip install -e git+https://github.com/HDI-Project/RDT#egg=rdt`

**Closed** 2019-02-01 13:19 UTC

**Comment by ManuelAlvarezC** [comment] 2019-02-05 12:40
For anybody arriving here in the future:

This was a compatibility issue between [RDT](https://github.com/HDI-Project/RDT) and pandas==0.24.0, and after the release of RDT v0.1.2 there is no need of any of the mentioned above.
