### ISSUE TITLE
Number of synthetized children rows

### ISSUE THREAD

**Issue by pajachiet** [HDI-Project/SDV#83] opened 2019-02-01 14:38 UTC
* SDV version: current master branch

### Description

I would like to understand how is modeled, then chosen the **number** of synthetized children rows.

This is not clear to me from this [paper](https://dai.lids.mit.edu/wp-content/uploads/2018/03/SDV.pdf). 

This is important for us, to better understand the confidentiality guarantees we can get from SDV.

Currently, we get 5 children rows for each sampled row for the top parent row. 

https://github.com/HDI-Project/SDV/blob/master/sdv/sampler.py#L202

What is the plan on this aspect ? Will it be learned ? or given as parameters ?

**Comment by ManuelAlvarezC** [comment] 2019-02-04 11:42
Hi @pajachiet, and thanks for your questions.

Currently we don't model the number of rows in a children table related to a parent. But it seems an interesting feature to have. Right now the only approach that I see feasible, would be adding a new column to the parent table for each children, counting the number of children and used them for modelling and sampling.

Have below a minimal working example of how to do it.

```python

import json

import pandas as pd

from sdv.data_navigator import CSVDataLoader
from sdv.modeler import Modeler
from sdv.sampler import Sampler

parent_table = pd.DataFrame([{'parent_id': i + 1} for i in range(3)])
parent_table.to_csv('parent.csv', header=True, index=False)

parent_table_metadata = {
    'fields': [
        {
            'name': 'parent_id', 
            'subtype': 'integer', 
            'type': 'number', 
            'regex': '^[0-9]{10}$'
        },

    ],
    'headers': True,
    'name': 'parent',
    'path': 'parent.csv',
    'primary_key': 'parent_id',
    'use': True
}

child_table = pd.DataFrame([
    {
        'child_id': 1,
        'parent_id': 1,
        'value': 'A'
    },
    {
        'child_id': 2,
        'parent_id': 1,
        'value': 'B'
    },
    {
        'child_id': 3,
        'parent_id': 1,
        'value': 'A'
    },
    {
        'child_id': 4,
        'parent_id': 2,
        'value': 'B',
    },
    {
        'child_id': 5,
        'parent_id': 2,
        'value': 'A'
    }
])
child_table.to_csv('child.csv', header=True, index=False)

child_table_metadata = {
    'fields': [
        {
            'name': 'child_id', 
            'subtype': 'integer', 
            'type': 'number', 
            'regex': '^[0-9]{10}$'
        },
        {
            'name': 'parent_id', 
            'ref': {
                'field': 'parent_id',
                'table': 'parent'
            },
            'subtype': 'integer',
            'type': 'number',
        },
        {
            'name': 'value', 
            'type': 'categorical', 
        },

    ],
    'headers': True,
    'name': 'child',
    'path': 'child.csv',
    'primary_key': 'child_id',
    'use': True
}

metadata = {
    'path': '',
    'tables': [
        parent_table_metadata,
        child_table_metadata
    ]
}

metadata_filename = 'metadata.json'
with open(metadata_filename, 'w') as f:
    json.dump(metadata, f)

# At his point we have two tables, `parent` and `child` that are related
# Fist, we are going to add a field `num_children` on the parent table, counting the amount of children rows related to each parent row

# We count the values for each child
foreign_related = child_table.groupby('parent_id').count()['value'].to_frame()

# We add it to the parent table
parent_table = parent_table.merge(foreign_related, how='left', left_on='parent_id', right_index=True)

# We clean possible missing values
parent_table.value.fillna(0, inplace=True)
parent_table.value = parent_table.value.astype(int)

# Rename the column
parent_table.rename(columns={'value': 'num_children'}, inplace=True)

# We save our data to disk
parent_table.to_csv('parent.csv', header=True, index=False)

## Update the metadata and we can go
metadata['tables'][0]['fields'].append({
    'name': 'num_children',
    'type': 'number',
    'subtype': 'integer'
})

with open(metadata_filename, 'w') as f:
    json.dump(metadata, f)

# Now its time to sample 
data_loader = CSVDataLoader(metadata_filename)
data_navigator = data_loader.load_data()
data_navigator.transform_data()

modeler = Modeler(data_navigator)
modeler.model_database()

sampler = Sampler(data_navigator, modeler)

# Now we are going to sample a few rows from the parent table:

sampled_data = {}
sampled_data['parent'] = sampler.sample_rows('parent', 10)

# At this pointthe sampled rows are also stored raw (with the conditional parameters for the children row) in sampler.sampled['parent']
# so we will iterate over each row, pass them to sampler.

def sample_children(sampled):
    def f(row):
        num_children = int(row['num_children'])
        result = sampler._sample_child_rows('parent', row, sampled, num_children)
        
    return f

sampled_data['parent'].apply(sample_children(sampled_data), axis=1)

# Now all that is left is to reset the indices
sampled_data = sampler.reset_indices_tables(sampled_data)
```

**Comment by pajachiet** [comment] 2019-02-04 18:17
Hello, thanks a lot for this clear answer ! with a full example ! 

I get an error in some cases when running your code (python 3.6, code on master branch) , when sampling for the 2nd time child rows with num_children=0. I did not investigate enough to understand why. I will investigate latter if we get further with this idea.

```
ValueError                                Traceback (most recent call last)
<ipython-input-40-dd1eed0c3314> in <module>
     10     return f
     11 
---> 12 sampled_data['parent'].apply(sample_children(sampled_data), axis=1)

…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6494                          args=args,
   6495                          kwds=kwds)
-> 6496         return op.get_result()
   6497 
   6498     def applymap(self, func):

…/SDV/venv/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    149             return self.apply_raw()
    150 
--> 151         return self.apply_standard()
    152 
    153     def apply_empty_result(self):

…/SDV/venv/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    255 
    256         # compute the result using the series generator
--> 257         self.apply_series_generator()
    258 
    259         # wrap results

…/SDV/venv/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    284             try:
    285                 for i, v in enumerate(series_gen):
--> 286                     results[i] = self.f(v)
    287                     keys.append(v.name)
    288             except Exception as e:

<ipython-input-40-dd1eed0c3314> in f(row)
      6         num_children = int(row['num_children'])
      7         print(num_children)
----> 8         result = sampler._sample_child_rows('parent', row, sampled, num_children)
      9 
     10     return f

…/SDV/sdv/sampler.py in _sample_child_rows(self, parent_name, parent_row, sampled_data, num_rows)
    220         children = self.dn.get_children(parent_name)
    221         for child in children:
--> 222             rows = self.sample_rows(child, num_rows)
    223 
    224             if child in sampled_data:

…/SDV/sdv/sampler.py in sample_rows(self, table_name, num_rows)
    146             print(synthesized_rows)
    147 
--> 148             return self.transform_synthesized_rows(synthesized_rows, table_name, num_rows)
    149 
    150         else:    # there is no parent

…/SDV/sdv/sampler.py in transform_synthesized_rows(self, synthesized_rows, table_name, num_rows)
     83         # reverse transform data
     84         reversed_data = self.dn.ht.reverse_transform_table(
---> 85             synthesized_rows, orig_meta, missing=False)
     86 
     87         synthesized_rows.update(reversed_data)

…/SDV/venv/src/rdt/rdt/hyper_transformer.py in reverse_transform_table(self, table, table_meta, missing)
    330 
    331         for field in table_meta['fields']:
--> 332             new_column = self._reverse_transform_column(table, field, table_name)
    333             if new_column is not None:
    334                 result[field['name']] = new_column

…/SDV/venv/src/rdt/rdt/hyper_transformer.py in _reverse_transform_column(self, table, metadata, table_name)
    198         content = pd.DataFrame(columns=[column_name], index=table.index)
    199         transformer = self.transformers[(table_name, column_name)]
--> 200         content[column_name] = transformer.reverse_transform(table[column_name].to_frame())
    201 
    202         if self.missing and null_name in table[column_name]:

…/SDV/venv/src/rdt/rdt/transformers/number.py in reverse_transform(self, col)
     58 
     59         output = pd.DataFrame(index=col.index)
---> 60         output[self.col_name] = col.apply(self.safe_round, axis=1)
     61 
     62         if self.subtype == 'int':

…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3358         else:
   3359             # set column
-> 3360             self._set_item(key, value)
   3361 
   3362     def _setitem_slice(self, key, value):

…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   3432         """
   3433 
-> 3434         self._ensure_valid_index(value)
   3435         value = self._sanitize_column(key, value)
   3436         NDFrame._set_item(self, key, value)

…/SDV/venv/lib/python3.6/site-packages/pandas/core/frame.py in _ensure_valid_index(self, value)
   3414                 value = Series(value)
   3415             except (ValueError, NotImplementedError, TypeError):
-> 3416                 raise ValueError('Cannot set a frame with no defined index '
   3417                                  'and a value that cannot be converted to a '
   3418                                  'Series')

ValueError: ('Cannot set a frame with no defined index and a value that cannot be converted to a Series', 'occurred at index 6')
```

**Comment by ManuelAlvarezC** [comment] 2019-02-05 12:56
Hi @pajachiet,

Are you still experiencing this issue? Please, don't close an issue after posting a message like your last one, as it won't be helpful for people coming in the future with similar issues.

If you weren't able to solve the issue you mentioned, do you mind sharing with us more details, including:
- List of steps to reproduce the issue
- Commit sha with `git rev-parse HEAD`
- Current versions of dependencies with  `pip freeze`
- If you are working with a dataset that is publicly available, a link to it.

However, if this issue has already been solved on our side, feel free to close this issue again after stating it in a message.

**Comment by pajachiet** [comment] 2019-02-05 14:33
Sorry for closing the issue. I thought you answered the question really well (or we could make it a feature request issue).

I get the issue with your code.

Commit `2b53cef12ec766fab6b05166975eb4ea5a665971`

```
$ pip freeze
pip freeze                                                                                           
boto3==1.9.87
botocore==1.12.87
copulas==0.2.1
cycler==0.10.0
docutils==0.14
exrex==0.10.5
Faker==1.0.2
jmespath==0.9.3
kiwisolver==1.0.1
matplotlib==3.0.2
numpy==1.16.1
pandas==0.24.1
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
rdt==0.1.2
s3transfer==0.1.13
scikit-learn==0.20.2
scipy==1.2.0
-e git+git@github.com:pajachiet/SDV.git@2b53cef12ec766fab6b05166975eb4ea5a665971#egg=sdv
six==1.12.0
text-unidecode==1.2
urllib3==1.24.1
```

I put your code on this [branch](https://github.com/pajachiet/SDV/blob/number_children/examples/number_children.py).

**Comment by ManuelAlvarezC** [comment] 2019-02-07 19:49
Hi again,

I'm closing this issue and opening a new one for a feature request. Meanwhile, using the example can make the trick. 

@pajachiet:
> when sampling for the 2nd time child rows with num_children=0

- sampler._sample_child_rows expects a `num_rows` estrictly greater or equal  to 1. So, passing `num_rows=0` will crash it. I was weirded when you said sampling for the 2nd time, because it should have crashed the first time too, but then I realized I misunderstood you.

To get a workaround for this you can make in `sample_children`:
```python
def sample_children(sampled):
    def f(row):
        num_children = int(row['num_children'])
        if num_children:
            result = sampler._sample_child_rows('parent', row, sampled, num_children)
        
    return f
```

And simpy not calling `_sample_child_rows` if `num_children=0`.

**Closed by ManuelAlvarezC** 2019-02-07 19:49 UTC
Labels: question
